jQuery.browser = {}, jQuery.browser.msie = !1, jQuery.browser.version = 0, navigator.userAgent.match(/MSIE ([0-9]+)\./) && (jQuery.browser.msie = !0, jQuery.browser.version = RegExp.$1);
const scene = document.getElementById("scene_intro"),
    parallaxInstance = new Parallax(scene),
    ParallaxItems = document.querySelectorAll(".parallax");
for (const item of ParallaxItems) new Parallax(item);

function windowSize() { $(".header__menu ul .has-child .child").css({ left: -(window.screen.width - $("header .container").width()) / 2 }) }
$(".intro__bg-1").scrollingParallax({ loopIt: !1, staticScrollLimit: !1, bgHeight: "20%", bgRepeat: !1, disableIE6: !0, bgWidth: "100%", staticSpeed: 1.5 }), $(".intro__bg-2").scrollingParallax({ loopIt: !1, staticScrollLimit: !1, bgHeight: "20%", bgRepeat: !1, disableIE6: !0, bgWidth: "100%", staticSpeed: 1 }), AOS.init({ once: !0, duration: 1e3, offset: 0 }), $(window).on("resize load", function() { AOS.refreshHard() }), $(window).on("scroll load", function() { AOS.refresh() }), $(".header__menu a.header__menu-link").on("mouseover", function() { if (!$(this).hasClass("active")) { let a = $(this).position(),
            b = $(this).width(),
            c = $(".header").height();
        $(".header__menu .slide2").css({ opacity: 1, left: +a.left, width: b, top: -c / 2 + 10 }).addClass("squeeze") } }), $(".header__menu a").on("mouseout", function() { $(".header__menu .slide2").css({ opacity: 0 }).removeClass("squeeze") }), $(window).on("load resize", windowSize), $(document).ready(function() { var a;
    $(".header__menu ul .has-child").on("mouseleave", function() { a = setTimeout(() => { $(this).find(".child").css({ visibility: "hidden", top: -hederHeight, pointerEvents: "none" }), $(".content__text").css("left", "0") }, 1e3) }), $(".header__menu ul .has-child").on("mouseover", function() { clearTimeout(a), a = null, $(".header__menu ul .has-child .child").css({ visibility: "hidden", top: -hederHeight, pointerEvents: "none" }), $(this).find(".child").css({ visibility: "visible", top: hederHeight, pointerEvents: "initial" }), $(".content__text").css("left", "-100%") }), $(".header__menu ul .has-child .child ul.container").mouseenter(function() { clearTimeout(a), a = null, $(this).find(".child").css({ visibility: "visible", top: hederHeight, pointerEvents: "initial" }), $(".content__text").css("left", "-100%") }), $(".hamburger-menu__nav .has-child.mobile-child").click(function() { $(this).find(".child").toggleClass("active-child") }) }), $(".services__slider").slick({ infinite: !1, slidesToShow: 5, slidesToScroll: 1, arrows: !1, dots: !0, responsive: [{ breakpoint: 1200, settings: { slidesToShow: 4 } }, { breakpoint: 992, settings: { slidesToShow: 3 } }, { breakpoint: 768, settings: { slidesToShow: 2 } }, { breakpoint: 480, settings: { slidesToShow: 2 } }] }), $(window).on("load resize", function() { 550 > $(window).width() ? ($(".vantage__wrapper:not(.slick-initialized)").slick({ dots: !0, slidesToShow: 2, infinite: !1, slidesToScroll: 1, arrows: !1 }), $(".office__list:not(.slick-initialized)").slick({ dots: !0, slidesToShow: 1, infinite: !1, slidesToScroll: 1, arrows: !1 }), $(window).scroll(function() { $(this).scrollTop() > 1 ? (header.addClass("header_fixed"), $("body").css({ paddingTop: hederHeight + "px", transition: "padding-top 0.5s ease-in-out" }), $("main").css("overflow", "hidden")) : (header.removeClass("header_fixed"), $("body").css({ paddingTop: 0, transition: "padding-top 0s " }), $("main").css("overflow", "initial")) })) : ($(".vantage__wrapper.slick-initialized").slick("unslick"), $(".office__list.slick-initialized").slick("unslick"), $(window).scroll(function() { $(this).scrollTop() > 1 ? (header.addClass("header_fixed"), $("body").css({ paddingTop: hederHeight + "px" }), $("main").css("overflow", "hidden"), $(".header__menu ul .has-child .child").css({ visibility: "hidden", top: -hederHeight })) : (header.removeClass("header_fixed"), $("body").css({ paddingTop: 0 }), $("main").css("overflow", "initial")) })) }), $(".origami__slider").slick({ infinite: !1, slidesToShow: 1, slidesToScroll: 1, arrows: !1, dots: !0 });
let header = $(".header"),
    hederHeight = header.height();
$(function() { $(".popup-modal").magnificPopup({ type: "inline", modal: !0, fixedContentPos: !1, closeOnBgClick: !0, callbacks: { open: function() { $("body").addClass("scroll_disabled") }, close: function() { $("body").removeClass("scroll_disabled") } } }) }); { let a = ["$", "%", "#", "@", "&", "(", ")", "=", "*", "/"],
        d = a.length,
        e = (a, b) => Math.floor(Math.random() * (b - a + 1)) + a;
    class f { constructor(a) { this.DOM = { el: a }, this.DOM.title = { word: this.DOM.el.querySelector(".content__text") }, charming(this.DOM.title.word), this.DOM.title.letters = Array.from(this.DOM.title.word.querySelectorAll("span")).sort(() => .5 - Math.random()), this.DOM.title.letters.forEach(a => a.dataset.initial = a.innerHTML), this.lettersTotal = this.DOM.title.letters.length, b.observe(this.DOM.el) }
        enter(b = "down") { this.DOM.title.word.style.opacity = 1, this.timeouts = [], this.complete = !1; let c = 0;
            this.DOM.title.letters.forEach((g, b) => { let f = setTimeout(() => { g.innerHTML = a[e(0, d - 1)], setTimeout(() => { g.innerHTML = g.dataset.initial, ++c, c === this.lettersTotal && (this.complete = !0) }, 100) }, 80 * b);
                this.timeouts.push(f) }) }
        exit(c = "down") { if (this.DOM.title.word.style.opacity = 0, !this.complete)
                for (let a = 0, b = this.timeouts.length; a <= b - 1; ++a) clearTimeout(this.timeouts[a]) } } let b, g = -1,
        h = [],
        c = Array.from(document.querySelectorAll(".content__section")); "IntersectionObserver" in window && (document.body.classList.add("ioapi"), b = new IntersectionObserver(a => { a.forEach(b => { if (b.intersectionRatio > .5) { let a = c.indexOf(b.target); if (a === g) return; let d = a > g;
                g >= 0 && h[g].exit(d ? "down" : "up"), h[a].enter(d ? "down" : "up"), g = a } }) }, { threshold: .5 }), c.forEach(a => h.push(new f(a)))), document.addEventListener("scroll", function() { window.pageYOffset, document.querySelector(".content__text"); let e = document.querySelectorAll(".content__text")[0],
            a = document.querySelectorAll(".content__text")[document.querySelectorAll(".content__text").length - 1],
            b = document.querySelector(".footer").offsetHeight,
            c = document.querySelector(".intro"),
            d = new window.IntersectionObserver(([a]) => { if (a.isIntersecting) { e.style.bottom = "-20vh"; return }
                e.style.bottom = "6vmax" }, { root: null, threshold: .5 });
        d.observe(c), $(window).scrollTop() + $(window).height() + b >= $(document).height() ? a.style.left = "-100vh" : a.style.left = "0" }) }

function waitForElm(a) { return new Promise(b => { if (document.querySelector(a)) return b(document.querySelector(a)); let c = new MutationObserver(d => { document.querySelector(a) && (b(document.querySelector(a)), c.disconnect()) });
        c.observe(document.body, { childList: !0, subtree: !0 }) }) }
$("[data-svg]").each(function() { var a = $(this),
        b = a.data("svg"),
        c = b.split("\\").pop().split("/").pop().replace(".svg", "");
    a.load(b, function(d, b) { "success" == b && a.find("svg").addClass("svg svg-" + c) }), waitForElm("#Map").then(b => { let a = function(b, c, d) { for (var a = 0; a < b.length; a++) c.call(d, a, b[a]) },
            c = function(a, b) { return Math.floor(Math.random() * (b - a + 1) + a) };
        a(document.querySelectorAll("#Map #pulse"), function(b, a) { a.groupTimeline = new TimelineMax({ paused: !0 }), a.groupTimeline.to(a, .25, { opacity: 0 }), new TimelineMax({ repeat: -1, delay: c(1, 3), repeatDelay: c(0, 1) }).to(a.querySelector(".Pin-back"), 3, { scale: 50, transformOrigin: "center center", opacity: 0 }) }); let d = document.querySelectorAll(".office__item");
        $("#Map [data-location]").on("mouseenter", function(b) { let c = this.getAttribute("data-location");
            a(d, function(b, a) { a.getAttribute("location") == c && (a.style.visibility = "visible") }) }).on("mouseout", function(b) { let c = this.getAttribute("data-location");
            a(d, function(b, a) { a.getAttribute("location") == c && (a.style.visibility = "hidden") }) }) }) }), $(document).ready(function() { $(".services__wrapper .services__slider_item").find(".services__slider_item-text:first").append(() => '<span class="more_text">....more</span>'), $(".more_text").on("click", function() { $(this).parent().parent().find(".hidden").css("max-height", "100%"), $(this).remove() }) }), $(".menu__icon, .hamburger-menu__close").on("click", function(a) { $(".hamburger-menu").fadeToggle(), $("body").toggleClass("scroll_disabled"), $("main").toggleClass("zindex"), $(".header_fixed").toggleClass("overflow") }), $(".hamburger-menu").on("click", function(a) { let b = $(".hamburger-menu__content"),
        c = $(".hamburger-menu");
    c.is(a.target) && !b.is(a.target) && 0 === b.has(a.target).length && "block" == $(".hamburger-menu").css("display") && ($(".hamburger-menu").fadeOut(), $("body").removeClass("scroll_disabled"), $("main").removeClass("zindex"), $(".header_fixed").removeClass("overflow")) }), $("#rocket").waypoint(function(a) { "down" === a ? $("#rocket img").animate({ top: "-=100vh" }, 2e3) : $("#rocket img").animate({ top: "0" }, 2e3) }, { offset: "10%" })